### ISSUE TITLE
automount service failed

### ISSUE THREAD

**Issue by matianfu** [matianfu/mininas_bootstrap#2]
```
root@winsuntech:~# journalctl -u automount-disk 
-- Logs begin at Mon 2015-12-28 22:35:59 CST, end at Mon 2015-12-28 22:48:19 CST. --
Dec 28 22:46:34 winsuntech systemd[1]: Starting Winsun Mininas Auto Mount Disk...
Dec 28 22:46:34 winsuntech bash[3114]: Traceback (most recent call last):
Dec 28 22:46:34 winsuntech bash[3114]: File "/srv/mini/aaa/mini/automountdisk.py", line 4, in <module>
Dec 28 22:46:34 winsuntech bash[3114]: if diskctl.checkrdinfo() == 100:
Dec 28 22:46:34 winsuntech bash[3114]: File "/srv/mini/aaa/mini/diskctl.py", line 101, in checkrdinfo
Dec 28 22:46:34 winsuntech bash[3114]: if uid in ds:
Dec 28 22:46:34 winsuntech bash[3114]: TypeError: 'in <string>' requires string as left operand, not NoneType
Dec 28 22:46:34 winsuntech systemd[1]: automount-disk.service: main process exited, code=exited, status=1/FAILURE
Dec 28 22:46:34 winsuntech systemd[1]: Failed to start Winsun Mininas Auto Mount Disk.
Dec 28 22:46:34 winsuntech systemd[1]: Unit automount-disk.service entered failed state.
Dec 28 22:47:56 winsuntech systemd[1]: Starting Winsun Mininas Auto Mount Disk...
Dec 28 22:47:56 winsuntech systemd[1]: Started Winsun Mininas Auto Mount Disk.
```

**Comment by JiangWeiGitHub** [comment]
Have to empty 'volume.json' file for first running.
